# Generated by Django 4.2.6 on 2023-10-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainobject',
            old_name='county',
            new_name='city',
        ),
    ]
