# Generated by Django 4.2.6 on 2023-10-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_county_mainobject_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='state',
        ),
    ]
